apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
      - name: tms
        image: tusharsaini9045/php-webapp:v-1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        volumeMounts:
        - name: volume1
          mountPath: /var/www/html/TMS/includes/
          readOnly: true
      volumes:
      - name: volume1
        configMap:
          name: myconfigmap
